/*
  Warnings:

  - The values [VOTE_NOTIFICATION,REPORT_NOTIFICATION,COMMENT_NOTIFICATION,MESSAGE_NOTIFICATION,FEEDBACK_NOTIFICATION,ANNOUNCEMENT_NOTIFICATION] on the enum `NotificationType` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `relatedEntityId` on the `Notifications` table. All the data in the column will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "NotificationType_new" AS ENUM ('VOTE_FORUM_POST_NOTIFICATION', 'COMMENT_FORUM_POST_NOTIFICATION', 'REPLY_COMMENT_FORUM_POST_NOTIFICATION', 'NEW_ANNOUNCEMENT_NOTIFICATION', 'VOTE_ANNOUNCEMENT_NOTIFICATION', 'COMMENT_ANNOUNCEMENT_NOTIFICATION', 'REPLY_COMMENT_ANNOUNCEMENT_NOTIFICATION', 'REPORT_SUBMITTED_CONFIRMATION', 'REPORT_RESOLVED_VIOLATION', 'REPORT_RESOLVED_NO_VIOLATION', 'YOUR_COMMENT_WAS_DELETED', 'MESSAGE_NEW_NOTIFICATION', 'FEEDBACK_SUBMITTED_NOTIFICATION', 'FEEDBACK_PROCESSING_NOTIFICATION', 'FEEDBACK_RESOLVED_NOTIFICATION', 'FEEDBACK_REJECTED_NOTIFICATION', 'NEW_FEEDBACK_RECEIVED', 'FEEDBACK_FORWARDED_TO_YOU', 'NEW_COMMENT_REPORT_FOR_ADMIN', 'ADMIN_NOTIFICATION', 'SYSTEM_ANNOUNCEMENT_NOTIFICATION');
ALTER TABLE "Notifications" ALTER COLUMN "notificationType" TYPE "NotificationType_new" USING ("notificationType"::text::"NotificationType_new");
ALTER TYPE "NotificationType" RENAME TO "NotificationType_old";
ALTER TYPE "NotificationType_new" RENAME TO "NotificationType";
DROP TYPE "public"."NotificationType_old";
COMMIT;

-- AlterTable
ALTER TABLE "Notifications" DROP COLUMN "relatedEntityId",
ADD COLUMN     "targetId" UUID;
