export type TypeOfNotification =
  // Vote notification
  | "VOTE_POST_NOTIFICATION"
  | "COMMENT_POST_NOTIFICATION"
  | "REPLY_COMMENT_NOTIFICATION"
  | "REPORT_COMMENT_NOTIFICATION"
  | "MESSAGE_NEW_NOTIFICATION"
  | "MESSAGE_SYSTEM_NOTIFICATION"
  | "FEEDBACK_SUBMITTED_NOTIFICATION"
  | "FEEDBACK_RECEIVED_NOTIFICATION"
  | "FEEDBACK_PROCESSING_NOTIFICATION"
  | "FEEDBACK_RESOLVED_NOTIFICATION"
  | "FEEDBACK_REJECTED_NOTIFICATION"
  | "SYSTEM_ANNOUNCEMENT_NOTIFICATION"
  | "ADMIN_NOTIFICATION";
