import { FeedbackPost } from "@/types/dashboard";

export const mockFeedbackPosts: FeedbackPost[] = [
  // --- TIÊU CỰC (15 items - 50%) ---
  {
    post_id: "p1",
    author: "Nguyễn Tuấn Kiệt",
    content:
      "Wifi khu C đúng là thảm họa, không bao giờ kết nối được quá 5 phút. Đóng tiền học phí đầy đủ mà cơ sở vật chất tệ quá.",
    post_link: "https://facebook.com/groups/ute/posts/101",
    posted_at: new Date("2026-04-20T08:30:00Z"),
    reaction_count: 156,
    comment_count: 45,
    engagement_score: 201,
    topic: "Cơ sở vật chất",
    sentiment_score: 0.1,
    ai_summary: "Phàn nàn gay gắt về chất lượng wifi tại khu C.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-20T09:00:00Z"),
  },
  {
    post_id: "p2",
    author: "Lê Minh Anh",
    content:
      "Trang đăng ký môn học lại sập rồi. Cứ mỗi lần tới đợt là như đánh trận, tốn cả buổi sáng mà không đăng ký được môn nào.",
    post_link: "https://facebook.com/groups/ute/posts/102",
    posted_at: new Date("2026-04-15T07:15:00Z"),
    reaction_count: 342,
    comment_count: 89,
    engagement_score: 431,
    topic: "Học vụ",
    sentiment_score: 0.05,
    ai_summary: "Báo lỗi hệ thống đăng ký môn học quá tải và gây bức xúc.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-15T08:00:00Z"),
  },
  {
    post_id: "p3",
    author: "Trần Hữu Thọ",
    content:
      "Bãi giữ xe khu E quá tải, bảo vệ thì thái độ khó chịu với sinh viên. Sáng nào cũng mất 15p mới gửi được xe.",
    post_link: "https://facebook.com/groups/ute/posts/103",
    posted_at: new Date("2026-04-22T06:45:00Z"),
    reaction_count: 88,
    comment_count: 23,
    engagement_score: 111,
    topic: "Dịch vụ",
    sentiment_score: 0.2,
    ai_summary:
      "Phản ánh tình trạng quá tải bãi xe và thái độ của nhân viên bảo vệ.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-22T10:00:00Z"),
  },
  {
    post_id: "p4",
    author: "Phạm Thảo Vy",
    content:
      "Máy chiếu phòng A304 bị sọc tím, giảng viên giảng bài sinh viên nhìn không ra chữ gì hết. Đã báo kỹ thuật cả tuần rồi chưa sửa.",
    post_link: "https://facebook.com/groups/ute/posts/104",
    posted_at: new Date("2026-04-18T13:30:00Z"),
    reaction_count: 45,
    comment_count: 12,
    engagement_score: 57,
    topic: "Cơ sở vật chất",
    sentiment_score: 0.15,
    ai_summary: "Yêu cầu sửa chữa máy chiếu hỏng tại phòng A304.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-18T15:00:00Z"),
  },
  {
    post_id: "p5",
    author: "Hoàng Gia Bảo",
    content:
      "Thang máy nhà trung tâm hay bị lỗi tầng, có hôm kẹt bên trong 10 phút mới ra được. Sợ thật sự!",
    post_link: "https://facebook.com/groups/ute/posts/105",
    posted_at: new Date("2026-04-25T09:00:00Z"),
    reaction_count: 210,
    comment_count: 56,
    engagement_score: 266,
    topic: "Cơ sở vật chất",
    sentiment_score: 0.1,
    ai_summary: "Cảnh báo về sự cố an toàn thang máy tại tòa nhà trung tâm.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-25T11:00:00Z"),
  },
  {
    post_id: "p6",
    author: "Vũ Nam Khánh",
    content:
      "Căng tin trường bán đồ ăn vừa đắt vừa ít. Mong nhà trường kiểm soát lại giá cả cho phù hợp túi tiền sinh viên.",
    post_link: "https://facebook.com/groups/ute/posts/106",
    posted_at: new Date("2026-04-12T11:45:00Z"),
    reaction_count: 120,
    comment_count: 34,
    engagement_score: 154,
    topic: "Dịch vụ",
    sentiment_score: 0.3,
    ai_summary: "Phàn nàn về giá cả và chất lượng đồ ăn tại căng tin.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-12T13:00:00Z"),
  },
  {
    post_id: "p7",
    author: "Bùi Tuyết Nhi",
    content:
      "Lịch thi bị trùng 2 môn cùng một buổi, gửi đơn cứu xét lên khoa mà 3 ngày rồi chưa thấy ai trả lời.",
    post_link: "https://facebook.com/groups/ute/posts/107",
    posted_at: new Date("2026-04-14T10:00:00Z"),
    reaction_count: 67,
    comment_count: 15,
    engagement_score: 82,
    topic: "Học vụ",
    sentiment_score: 0.25,
    ai_summary: "Bức xúc vì sự chậm trễ giải quyết trùng lịch thi của khoa.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-14T14:00:00Z"),
  },
  {
    post_id: "p8",
    author: "Đặng Thế Hiển",
    content:
      "Hành lang dãy D rất tối về chiều, đèn bị cháy nhiều bóng mà không thấy thay mới, đi lại khá nguy hiểm.",
    post_link: "https://facebook.com/groups/ute/posts/108",
    posted_at: new Date("2026-04-11T17:30:00Z"),
    reaction_count: 23,
    comment_count: 4,
    engagement_score: 27,
    topic: "Cơ sở vật chất",
    sentiment_score: 0.35,
    ai_summary: "Phản ánh tình trạng thiếu ánh sáng tại dãy D do đèn hỏng.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-11T20:00:00Z"),
  },
  {
    post_id: "p9",
    author: "Lý Hồng Quang",
    content:
      "Giảng viên môn Kỹ thuật số dạy quá nhanh, không kịp chép bài chứ đừng nói là hiểu. Góp ý thì thầy bảo tự về đọc sách.",
    post_link: "https://facebook.com/groups/ute/posts/109",
    posted_at: new Date("2026-04-08T15:20:00Z"),
    reaction_count: 92,
    comment_count: 41,
    engagement_score: 133,
    topic: "Giảng viên",
    sentiment_score: 0.2,
    ai_summary:
      "Phê bình phương pháp giảng dạy không phù hợp của giảng viên môn Kỹ thuật số.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-08T18:00:00Z"),
  },
  {
    post_id: "p10",
    author: "Phan Kim Ngân",
    content:
      "Nước sinh hoạt ở KTX khu A có mùi lạ, màu hơi đục. Mong Ban quản lý kiểm tra lại bồn chứa nước.",
    post_link: "https://facebook.com/groups/ute/posts/110",
    posted_at: new Date("2026-04-05T06:00:00Z"),
    reaction_count: 145,
    comment_count: 28,
    engagement_score: 173,
    topic: "Ký túc xá",
    sentiment_score: 0.1,
    ai_summary: "Cảnh báo về chất lượng nước sinh hoạt không đảm bảo tại KTX.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-05T08:00:00Z"),
  },
  {
    post_id: "p11",
    author: "Ngô Văn Tài",
    content:
      "Thư viện mở cửa trễ hơn thông báo 30 phút làm mình phải đứng đợi dưới nắng. Rất thiếu chuyên nghiệp.",
    post_link: "https://facebook.com/groups/ute/posts/111",
    posted_at: new Date("2026-04-16T07:45:00Z"),
    reaction_count: 38,
    comment_count: 9,
    engagement_score: 47,
    topic: "Dịch vụ",
    sentiment_score: 0.3,
    ai_summary:
      "Phàn nàn về giờ giấc làm việc không đúng quy định của thư viện.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-16T09:00:00Z"),
  },
  {
    post_id: "p12",
    author: "Trịnh Gia Huy",
    content:
      "Học phí năm nay tăng mà chất lượng giảng dạy thấy vẫn vậy, thậm chí một số phòng máy còn tệ hơn năm ngoái.",
    post_link: "https://facebook.com/groups/ute/posts/112",
    posted_at: new Date("2026-04-03T14:00:00Z"),
    reaction_count: 512,
    comment_count: 120,
    engagement_score: 632,
    topic: "Học vụ",
    sentiment_score: 0.1,
    ai_summary:
      "Bức xúc về việc tăng học phí không đi kèm cải thiện chất lượng.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-03T16:00:00Z"),
  },
  {
    post_id: "p13",
    author: "Lương Thu Trang",
    content:
      "Phòng học khu B quá nóng, quạt trần quay lờ đờ như sắp rớt. Học mà mồ hôi nhễ nhại không tập trung nổi.",
    post_link: "https://facebook.com/groups/ute/posts/113",
    posted_at: new Date("2026-04-07T13:00:00Z"),
    reaction_count: 85,
    comment_count: 19,
    engagement_score: 104,
    topic: "Cơ sở vật chất",
    sentiment_score: 0.2,
    ai_summary: "Phản ánh tình trạng nóng bức và thiết bị quạt kém tại khu B.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-07T15:00:00Z"),
  },
  {
    post_id: "p14",
    author: "Dương Chí Thành",
    content:
      "Thủ tục xin bảng điểm quá rườm rà, bắt chạy qua chạy lại giữa các phòng ban. Sao không làm online hết đi?",
    post_link: "https://facebook.com/groups/ute/posts/114",
    posted_at: new Date("2026-04-10T09:30:00Z"),
    reaction_count: 110,
    comment_count: 22,
    engagement_score: 132,
    topic: "Học vụ",
    sentiment_score: 0.25,
    ai_summary:
      "Góp ý về việc cải cách thủ tục hành chính sang hình thức online.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-10T11:00:00Z"),
  },
  {
    post_id: "p15",
    author: "Mai Phương Thảo",
    content:
      "Cây ATM trước cổng trường thường xuyên hết tiền vào cuối tuần. Rất bất tiện cho sinh viên ở xa.",
    post_link: "https://facebook.com/groups/ute/posts/115",
    posted_at: new Date("2026-04-19T20:00:00Z"),
    reaction_count: 42,
    comment_count: 7,
    engagement_score: 49,
    topic: "Dịch vụ",
    sentiment_score: 0.35,
    ai_summary: "Phản ánh tình trạng cây ATM thường xuyên thiếu tiền mặt.",
    sentiment_label: "Tiêu cực",
    analyzed_at: new Date("2026-04-20T08:00:00Z"),
  },

  // --- TÍCH CỰC (10 items - 33%) ---
  {
    post_id: "p16",
    author: "Lê Xuân Mạnh",
    content:
      "Vườn hoa trước sảnh nhà trung tâm dạo này đẹp quá, nhà trường chăm sóc rất kỹ. Chỗ này chụp ảnh kỷ yếu bao đẹp.",
    post_link: "https://facebook.com/groups/ute/posts/116",
    posted_at: new Date("2026-04-24T16:00:00Z"),
    reaction_count: 230,
    comment_count: 12,
    engagement_score: 242,
    topic: "Cơ sở vật chất",
    sentiment_score: 0.95,
    ai_summary: "Khen ngợi cảnh quan khuôn viên trường.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-25T08:00:00Z"),
  },
  {
    post_id: "p17",
    author: "Hoàng Minh Đức",
    content:
      "Cảm ơn thầy Sơn khoa Cơ khí đã hướng dẫn nhóm em nhiệt tình trong cuộc thi Mini Robot vừa qua. Thầy cực tâm huyết luôn!",
    post_link: "https://facebook.com/groups/ute/posts/117",
    posted_at: new Date("2026-04-21T14:30:00Z"),
    reaction_count: 180,
    comment_count: 8,
    engagement_score: 188,
    topic: "Giảng viên",
    sentiment_score: 0.9,
    ai_summary: "Bày tỏ lòng biết ơn đối với giảng viên hướng dẫn khoa Cơ khí.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-21T18:00:00Z"),
  },
  {
    post_id: "p18",
    author: "Đặng Thu Hà",
    content:
      "Dịch vụ mượn sách online của thư viện rất nhanh gọn. Mình đặt tối qua mà sáng nay đã có thông báo nhận sách.",
    post_link: "https://facebook.com/groups/ute/posts/118",
    posted_at: new Date("2026-04-17T09:00:00Z"),
    reaction_count: 56,
    comment_count: 4,
    engagement_score: 60,
    topic: "Dịch vụ",
    sentiment_score: 0.85,
    ai_summary: "Đánh giá cao sự tiện lợi của dịch vụ thư viện trực tuyến.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-17T11:00:00Z"),
  },
  {
    post_id: "p19",
    author: "Võ Văn Sang",
    content:
      "Phòng gym trường mình mới trang bị thêm dàn máy chạy bộ xịn xò lắm. Chiều nào cũng ra làm vài vòng là khỏe người.",
    post_link: "https://facebook.com/groups/ute/posts/119",
    posted_at: new Date("2026-04-23T17:15:00Z"),
    reaction_count: 112,
    comment_count: 18,
    engagement_score: 130,
    topic: "Cơ sở vật chất",
    sentiment_score: 0.9,
    ai_summary: "Hào hứng với trang thiết bị mới tại phòng gym.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-24T08:00:00Z"),
  },
  {
    post_id: "p20",
    author: "Nguyễn Lê Quỳnh",
    content:
      "Hội thảo về AI hôm nay thực sự rất bổ ích. Mong trường tổ chức thêm nhiều buổi chia sẻ kiến thức thực tế như thế này.",
    post_link: "https://facebook.com/groups/ute/posts/120",
    posted_at: new Date("2026-04-26T15:00:00Z"),
    reaction_count: 245,
    comment_count: 22,
    engagement_score: 267,
    topic: "Học vụ",
    sentiment_score: 0.95,
    ai_summary: "Phản hồi tích cực về chất lượng các buổi hội thảo chuyên đề.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-26T18:00:00Z"),
  },
  {
    post_id: "p21",
    author: "Phan Anh Tú",
    content:
      "Đội ngũ tình nguyện hỗ trợ tân sinh viên năm nay làm việc rất nhiệt tình và chu đáo. Tự hào là sinh viên UTE!",
    post_link: "https://facebook.com/groups/ute/posts/121",
    posted_at: new Date("2026-04-13T08:00:00Z"),
    reaction_count: 320,
    comment_count: 15,
    engagement_score: 335,
    topic: "Dịch vụ",
    sentiment_score: 0.9,
    ai_summary: "Khen ngợi tinh thần tình nguyện của sinh viên trường.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-13T10:00:00Z"),
  },
  {
    post_id: "p22",
    author: "Trần Bảo Ngọc",
    content:
      "Hệ thống LMS đợt này chạy rất mượt, nộp bài không còn bị giật lag như trước nữa. Cảm ơn đội ngũ IT trường.",
    post_link: "https://facebook.com/groups/ute/posts/122",
    posted_at: new Date("2026-04-22T21:30:00Z"),
    reaction_count: 89,
    comment_count: 7,
    engagement_score: 96,
    topic: "Học vụ",
    sentiment_score: 0.85,
    ai_summary: "Hài lòng với sự cải thiện hiệu năng của hệ thống LMS.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-23T08:00:00Z"),
  },
  {
    post_id: "p23",
    author: "Lý Gia Kiệt",
    content:
      "Các câu lạc bộ của trường mình hoạt động rất năng nổ. Tham gia CLB giúp mình học được bao nhiêu kỹ năng mềm.",
    post_link: "https://facebook.com/groups/ute/posts/123",
    posted_at: new Date("2026-04-09T19:00:00Z"),
    reaction_count: 175,
    comment_count: 25,
    engagement_score: 200,
    topic: "Dịch vụ",
    sentiment_score: 0.9,
    ai_summary: "Đánh giá cao môi trường hoạt động ngoại khóa tại trường.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-10T09:00:00Z"),
  },
  {
    post_id: "p24",
    author: "Ngô Mỹ Linh",
    content:
      "Không gian tự học ở thư viện mới được decor lại nhìn xịn như quán cafe, học tập trung hơn hẳn.",
    post_link: "https://facebook.com/groups/ute/posts/124",
    posted_at: new Date("2026-04-18T10:00:00Z"),
    reaction_count: 154,
    comment_count: 11,
    engagement_score: 165,
    topic: "Cơ sở vật chất",
    sentiment_score: 0.95,
    ai_summary: "Ấn tượng với thiết kế mới của không gian tự học.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-18T14:00:00Z"),
  },
  {
    post_id: "p25",
    author: "Đỗ Minh Quang",
    content:
      "Các chú bảo vệ KTX dạo này rất thân thiện, hay nhắc nhở sinh viên khóa xe cẩn thận. Cảm thấy rất an tâm.",
    post_link: "https://facebook.com/groups/ute/posts/125",
    posted_at: new Date("2026-04-25T22:30:00Z"),
    reaction_count: 132,
    comment_count: 5,
    engagement_score: 137,
    topic: "Ký túc xá",
    sentiment_score: 0.85,
    ai_summary:
      "Ghi nhận sự thay đổi tích cực trong thái độ của nhân viên an ninh KTX.",
    sentiment_label: "Tích cực",
    analyzed_at: new Date("2026-04-26T08:00:00Z"),
  },

  // --- TRUNG LẬP (5 items - 17%) ---
  {
    post_id: "p26",
    author: "Bùi Văn Nam",
    content:
      "Mọi người cho mình hỏi lịch nghỉ lễ 30/4 năm nay của trường mình có thông báo chính thức chưa nhỉ?",
    post_link: "https://facebook.com/groups/ute/posts/126",
    posted_at: new Date("2026-04-20T10:00:00Z"),
    reaction_count: 15,
    comment_count: 32,
    engagement_score: 47,
    topic: "Học vụ",
    sentiment_score: 0.5,
    ai_summary: "Câu hỏi về lịch nghỉ lễ chính thức.",
    sentiment_label: "Trung lập",
    analyzed_at: new Date("2026-04-20T11:00:00Z"),
  },
  {
    post_id: "p27",
    author: "Vũ Thị Lan",
    content:
      "Dịch vụ giặt sấy ở KTX giá 15k/lần, cũng tạm ổn nhưng mong có thêm máy để không phải đợi lâu.",
    post_link: "https://facebook.com/groups/ute/posts/127",
    posted_at: new Date("2026-04-14T16:00:00Z"),
    reaction_count: 24,
    comment_count: 8,
    engagement_score: 32,
    topic: "Ký túc xá",
    sentiment_score: 0.45,
    ai_summary: "Góp ý về việc tăng số lượng máy giặt tại KTX.",
    sentiment_label: "Trung lập",
    analyzed_at: new Date("2026-04-14T18:00:00Z"),
  },
  {
    post_id: "p28",
    author: "Trần Minh Hoàng",
    content:
      "Trường mình có câu lạc bộ nào về nhiếp ảnh không mọi người? Muốn tìm hội anh em cùng đam mê.",
    post_link: "https://facebook.com/groups/ute/posts/128",
    posted_at: new Date("2026-04-11T20:30:00Z"),
    reaction_count: 12,
    comment_count: 19,
    engagement_score: 31,
    topic: "Dịch vụ",
    sentiment_score: 0.55,
    ai_summary: "Tìm kiếm thông tin về các câu lạc bộ sở thích.",
    sentiment_label: "Trung lập",
    analyzed_at: new Date("2026-04-12T08:00:00Z"),
  },
  {
    post_id: "p29",
    author: "Phạm Hữu Nghĩa",
    content:
      "Nhà xe khu E dạo này thấy có dọn dẹp lại, nhìn cũng thoáng hơn chút nhưng vẫn cần mái che.",
    post_link: "https://facebook.com/groups/ute/posts/129",
    posted_at: new Date("2026-04-22T08:15:00Z"),
    reaction_count: 35,
    comment_count: 6,
    engagement_score: 41,
    topic: "Dịch vụ",
    sentiment_score: 0.5,
    ai_summary:
      "Ghi nhận sự cải thiện nhẹ tại bãi xe nhưng vẫn nhấn mạnh nhu cầu mái che.",
    sentiment_label: "Trung lập",
    analyzed_at: new Date("2026-04-22T10:00:00Z"),
  },
  {
    post_id: "p30",
    author: "Lê Thị Thắm",
    content:
      "Phòng đào tạo vừa có thông báo mới về chuẩn đầu ra tiếng Anh, các bạn K22 lưu ý nhé.",
    post_link: "https://facebook.com/groups/ute/posts/130",
    posted_at: new Date("2026-04-25T14:00:00Z"),
    reaction_count: 68,
    comment_count: 25,
    engagement_score: 93,
    topic: "Học vụ",
    sentiment_score: 0.5,
    ai_summary: "Chia sẻ thông tin về quy định chuẩn đầu ra ngoại ngữ.",
    sentiment_label: "Trung lập",
    analyzed_at: new Date("2026-04-25T16:00:00Z"),
  },
];
