import { FeedbackPost } from "@/types/social-listening";

export const mockFeedbackPosts: FeedbackPost[] = [
  // --- TIÊU CỰC (15 items - 50%) ---
  {
    postId: "p1",
    author: "Nguyễn Tuấn Kiệt",
    content:
      "Wifi khu C đúng là thảm họa, không bao giờ kết nối được quá 5 phút. Đóng tiền học phí đầy đủ mà cơ sở vật chất tệ quá.",
    postLink: "https://facebook.com/groups/ute/posts/101",
    postedAt: new Date("2026-04-20T08:30:00Z"),
    reactionCount: 156,
    commentCount: 45,
    engagementScore: 201,
    topic: "Cơ sở vật chất",
    sentimentScore: 0.1,
    aiSummary: "Phàn nàn gay gắt về chất lượng wifi tại khu C.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-20T09:00:00Z"),
  },
  {
    postId: "p2",
    author: "Lê Minh Anh",
    content:
      "Trang đăng ký môn học lại sập rồi. Cứ mỗi lần tới đợt là như đánh trận, tốn cả buổi sáng mà không đăng ký được môn nào.",
    postLink: "https://facebook.com/groups/ute/posts/102",
    postedAt: new Date("2026-04-15T07:15:00Z"),
    reactionCount: 342,
    commentCount: 89,
    engagementScore: 431,
    topic: "Học vụ",
    sentimentScore: 0.05,
    aiSummary: "Báo lỗi hệ thống đăng ký môn học quá tải và gây bức xúc.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-15T08:00:00Z"),
  },
  {
    postId: "p3",
    author: "Trần Hữu Thọ",
    content:
      "Bãi giữ xe khu E quá tải, bảo vệ thì thái độ khó chịu với sinh viên. Sáng nào cũng mất 15p mới gửi được xe.",
    postLink: "https://facebook.com/groups/ute/posts/103",
    postedAt: new Date("2026-04-22T06:45:00Z"),
    reactionCount: 88,
    commentCount: 23,
    engagementScore: 111,
    topic: "Dịch vụ",
    sentimentScore: 0.2,
    aiSummary:
      "Phản ánh tình trạng quá tải bãi xe và thái độ của nhân viên bảo vệ.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-22T10:00:00Z"),
  },
  {
    postId: "p4",
    author: "Phạm Thảo Vy",
    content:
      "Máy chiếu phòng A304 bị sọc tím, giảng viên giảng bài sinh viên nhìn không ra chữ gì hết. Đã báo kỹ thuật cả tuần rồi chưa sửa.",
    postLink: "https://facebook.com/groups/ute/posts/104",
    postedAt: new Date("2026-04-18T13:30:00Z"),
    reactionCount: 45,
    commentCount: 12,
    engagementScore: 57,
    topic: "Cơ sở vật chất",
    sentimentScore: 0.15,
    aiSummary: "Yêu cầu sửa chữa máy chiếu hỏng tại phòng A304.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-18T15:00:00Z"),
  },
  {
    postId: "p5",
    author: "Hoàng Gia Bảo",
    content:
      "Thang máy nhà trung tâm hay bị lỗi tầng, có hôm kẹt bên trong 10 phút mới ra được. Sợ thật sự!",
    postLink: "https://facebook.com/groups/ute/posts/105",
    postedAt: new Date("2026-04-25T09:00:00Z"),
    reactionCount: 210,
    commentCount: 56,
    engagementScore: 266,
    topic: "Cơ sở vật chất",
    sentimentScore: 0.1,
    aiSummary: "Cảnh báo về sự cố an toàn thang máy tại tòa nhà trung tâm.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-25T11:00:00Z"),
  },
  {
    postId: "p6",
    author: "Vũ Nam Khánh",
    content:
      "Căng tin trường bán đồ ăn vừa đắt vừa ít. Mong nhà trường kiểm soát lại giá cả cho phù hợp túi tiền sinh viên.",
    postLink: "https://facebook.com/groups/ute/posts/106",
    postedAt: new Date("2026-04-12T11:45:00Z"),
    reactionCount: 120,
    commentCount: 34,
    engagementScore: 154,
    topic: "Dịch vụ",
    sentimentScore: 0.3,
    aiSummary: "Phàn nàn về giá cả và chất lượng đồ ăn tại căng tin.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-12T13:00:00Z"),
  },
  {
    postId: "p7",
    author: "Bùi Tuyết Nhi",
    content:
      "Lịch thi bị trùng 2 môn cùng một buổi, gửi đơn cứu xét lên khoa mà 3 ngày rồi chưa thấy ai trả lời.",
    postLink: "https://facebook.com/groups/ute/posts/107",
    postedAt: new Date("2026-04-14T10:00:00Z"),
    reactionCount: 67,
    commentCount: 15,
    engagementScore: 82,
    topic: "Học vụ",
    sentimentScore: 0.25,
    aiSummary: "Bức xúc vì sự chậm trễ giải quyết trùng lịch thi của khoa.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-14T14:00:00Z"),
  },
  {
    postId: "p8",
    author: "Đặng Thế Hiển",
    content:
      "Hành lang dãy D rất tối về chiều, đèn bị cháy nhiều bóng mà không thấy thay mới, đi lại khá nguy hiểm.",
    postLink: "https://facebook.com/groups/ute/posts/108",
    postedAt: new Date("2026-04-11T17:30:00Z"),
    reactionCount: 23,
    commentCount: 4,
    engagementScore: 27,
    topic: "Cơ sở vật chất",
    sentimentScore: 0.35,
    aiSummary: "Phản ánh tình trạng thiếu ánh sáng tại dãy D do đèn hỏng.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-11T20:00:00Z"),
  },
  {
    postId: "p9",
    author: "Lý Hồng Quang",
    content:
      "Giảng viên môn Kỹ thuật số dạy quá nhanh, không kịp chép bài chứ đừng nói là hiểu. Góp ý thì thầy bảo tự về đọc sách.",
    postLink: "https://facebook.com/groups/ute/posts/109",
    postedAt: new Date("2026-04-08T15:20:00Z"),
    reactionCount: 92,
    commentCount: 41,
    engagementScore: 133,
    topic: "Giảng viên",
    sentimentScore: 0.2,
    aiSummary:
      "Phê bình phương pháp giảng dạy không phù hợp của giảng viên môn Kỹ thuật số.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-08T18:00:00Z"),
  },
  {
    postId: "p10",
    author: "Phan Kim Ngân",
    content:
      "Nước sinh hoạt ở KTX khu A có mùi lạ, màu hơi đục. Mong Ban quản lý kiểm tra lại bồn chứa nước.",
    postLink: "https://facebook.com/groups/ute/posts/110",
    postedAt: new Date("2026-04-05T06:00:00Z"),
    reactionCount: 145,
    commentCount: 28,
    engagementScore: 173,
    topic: "Ký túc xá",
    sentimentScore: 0.1,
    aiSummary: "Cảnh báo về chất lượng nước sinh hoạt không đảm bảo tại KTX.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-05T08:00:00Z"),
  },
  {
    postId: "p11",
    author: "Ngô Văn Tài",
    content:
      "Thư viện mở cửa trễ hơn thông báo 30 phút làm mình phải đứng đợi dưới nắng. Rất thiếu chuyên nghiệp.",
    postLink: "https://facebook.com/groups/ute/posts/111",
    postedAt: new Date("2026-04-16T07:45:00Z"),
    reactionCount: 38,
    commentCount: 9,
    engagementScore: 47,
    topic: "Dịch vụ",
    sentimentScore: 0.3,
    aiSummary:
      "Phàn nàn về giờ giấc làm việc không đúng quy định của thư viện.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-16T09:00:00Z"),
  },
  {
    postId: "p12",
    author: "Trịnh Gia Huy",
    content:
      "Học phí năm nay tăng mà chất lượng giảng dạy thấy vẫn vậy, thậm chí một số phòng máy còn tệ hơn năm ngoái.",
    postLink: "https://facebook.com/groups/ute/posts/112",
    postedAt: new Date("2026-04-03T14:00:00Z"),
    reactionCount: 512,
    commentCount: 120,
    engagementScore: 632,
    topic: "Học vụ",
    sentimentScore: 0.1,
    aiSummary:
      "Bức xúc về việc tăng học phí không đi kèm cải thiện chất lượng.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-03T16:00:00Z"),
  },
  {
    postId: "p13",
    author: "Lương Thu Trang",
    content:
      "Phòng học khu B quá nóng, quạt trần quay lờ đờ như sắp rớt. Học mà mồ hôi nhễ nhại không tập trung nổi.",
    postLink: "https://facebook.com/groups/ute/posts/113",
    postedAt: new Date("2026-04-07T13:00:00Z"),
    reactionCount: 85,
    commentCount: 19,
    engagementScore: 104,
    topic: "Cơ sở vật chất",
    sentimentScore: 0.2,
    aiSummary: "Phản ánh tình trạng nóng bức và thiết bị quạt kém tại khu B.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-07T15:00:00Z"),
  },
  {
    postId: "p14",
    author: "Dương Chí Thành",
    content:
      "Thủ tục xin bảng điểm quá rườm rà, bắt chạy qua chạy lại giữa các phòng ban. Sao không làm online hết đi?",
    postLink: "https://facebook.com/groups/ute/posts/114",
    postedAt: new Date("2026-04-10T09:30:00Z"),
    reactionCount: 110,
    commentCount: 22,
    engagementScore: 132,
    topic: "Học vụ",
    sentimentScore: 0.25,
    aiSummary:
      "Góp ý về việc cải cách thủ tục hành chính sang hình thức online.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-10T11:00:00Z"),
  },
  {
    postId: "p15",
    author: "Mai Phương Thảo",
    content:
      "Cây ATM trước cổng trường thường xuyên hết tiền vào cuối tuần. Rất bất tiện cho sinh viên ở xa.",
    postLink: "https://facebook.com/groups/ute/posts/115",
    postedAt: new Date("2026-04-19T20:00:00Z"),
    reactionCount: 42,
    commentCount: 7,
    engagementScore: 49,
    topic: "Dịch vụ",
    sentimentScore: 0.35,
    aiSummary: "Phản ánh tình trạng cây ATM thường xuyên thiếu tiền mặt.",
    sentimentLabel: "Tiêu cực",
    analyzedAt: new Date("2026-04-20T08:00:00Z"),
  },

  // --- TÍCH CỰC (10 items - 33%) ---
  {
    postId: "p16",
    author: "Lê Xuân Mạnh",
    content:
      "Vườn hoa trước sảnh nhà trung tâm dạo này đẹp quá, nhà trường chăm sóc rất kỹ. Chỗ này chụp ảnh kỷ yếu bao đẹp.",
    postLink: "https://facebook.com/groups/ute/posts/116",
    postedAt: new Date("2026-04-24T16:00:00Z"),
    reactionCount: 230,
    commentCount: 12,
    engagementScore: 242,
    topic: "Cơ sở vật chất",
    sentimentScore: 0.95,
    aiSummary: "Khen ngợi cảnh quan khuôn viên trường.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-25T08:00:00Z"),
  },
  {
    postId: "p17",
    author: "Hoàng Minh Đức",
    content:
      "Cảm ơn thầy Sơn khoa Cơ khí đã hướng dẫn nhóm em nhiệt tình trong cuộc thi Mini Robot vừa qua. Thầy cực tâm huyết luôn!",
    postLink: "https://facebook.com/groups/ute/posts/117",
    postedAt: new Date("2026-04-21T14:30:00Z"),
    reactionCount: 180,
    commentCount: 8,
    engagementScore: 188,
    topic: "Giảng viên",
    sentimentScore: 0.9,
    aiSummary: "Bày tỏ lòng biết ơn đối với giảng viên hướng dẫn khoa Cơ khí.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-21T18:00:00Z"),
  },
  {
    postId: "p18",
    author: "Đặng Thu Hà",
    content:
      "Dịch vụ mượn sách online của thư viện rất nhanh gọn. Mình đặt tối qua mà sáng nay đã có thông báo nhận sách.",
    postLink: "https://facebook.com/groups/ute/posts/118",
    postedAt: new Date("2026-04-17T09:00:00Z"),
    reactionCount: 56,
    commentCount: 4,
    engagementScore: 60,
    topic: "Dịch vụ",
    sentimentScore: 0.85,
    aiSummary: "Đánh giá cao sự tiện lợi của dịch vụ thư viện trực tuyến.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-17T11:00:00Z"),
  },
  {
    postId: "p19",
    author: "Võ Văn Sang",
    content:
      "Phòng gym trường mình mới trang bị thêm dàn máy chạy bộ xịn xò lắm. Chiều nào cũng ra làm vài vòng là khỏe người.",
    postLink: "https://facebook.com/groups/ute/posts/119",
    postedAt: new Date("2026-04-23T17:15:00Z"),
    reactionCount: 112,
    commentCount: 18,
    engagementScore: 130,
    topic: "Cơ sở vật chất",
    sentimentScore: 0.9,
    aiSummary: "Hào hứng với trang thiết bị mới tại phòng gym.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-24T08:00:00Z"),
  },
  {
    postId: "p20",
    author: "Nguyễn Lê Quỳnh",
    content:
      "Hội thảo về AI hôm nay thực sự rất bổ ích. Mong trường tổ chức thêm nhiều buổi chia sẻ kiến thức thực tế như thế này.",
    postLink: "https://facebook.com/groups/ute/posts/120",
    postedAt: new Date("2026-04-26T15:00:00Z"),
    reactionCount: 245,
    commentCount: 22,
    engagementScore: 267,
    topic: "Học vụ",
    sentimentScore: 0.95,
    aiSummary: "Phản hồi tích cực về chất lượng các buổi hội thảo chuyên đề.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-26T18:00:00Z"),
  },
  {
    postId: "p21",
    author: "Phan Anh Tú",
    content:
      "Đội ngũ tình nguyện hỗ trợ tân sinh viên năm nay làm việc rất nhiệt tình và chu đáo. Tự hào là sinh viên UTE!",
    postLink: "https://facebook.com/groups/ute/posts/121",
    postedAt: new Date("2026-04-13T08:00:00Z"),
    reactionCount: 320,
    commentCount: 15,
    engagementScore: 335,
    topic: "Dịch vụ",
    sentimentScore: 0.9,
    aiSummary: "Khen ngợi tinh thần tình nguyện của sinh viên trường.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-13T10:00:00Z"),
  },
  {
    postId: "p22",
    author: "Trần Bảo Ngọc",
    content:
      "Hệ thống LMS đợt này chạy rất mượt, nộp bài không còn bị giật lag như trước nữa. Cảm ơn đội ngũ IT trường.",
    postLink: "https://facebook.com/groups/ute/posts/122",
    postedAt: new Date("2026-04-22T21:30:00Z"),
    reactionCount: 89,
    commentCount: 7,
    engagementScore: 96,
    topic: "Học vụ",
    sentimentScore: 0.85,
    aiSummary: "Hài lòng với sự cải thiện hiệu năng của hệ thống LMS.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-23T08:00:00Z"),
  },
  {
    postId: "p23",
    author: "Lý Gia Kiệt",
    content:
      "Các câu lạc bộ của trường mình hoạt động rất năng nổ. Tham gia CLB giúp mình học được bao nhiêu kỹ năng mềm.",
    postLink: "https://facebook.com/groups/ute/posts/123",
    postedAt: new Date("2026-04-09T19:00:00Z"),
    reactionCount: 175,
    commentCount: 25,
    engagementScore: 200,
    topic: "Dịch vụ",
    sentimentScore: 0.9,
    aiSummary: "Đánh giá cao môi trường hoạt động ngoại khóa tại trường.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-10T09:00:00Z"),
  },
  {
    postId: "p24",
    author: "Ngô Mỹ Linh",
    content:
      "Không gian tự học ở thư viện mới được decor lại nhìn xịn như quán cafe, học tập trung hơn hẳn.",
    postLink: "https://facebook.com/groups/ute/posts/124",
    postedAt: new Date("2026-04-18T10:00:00Z"),
    reactionCount: 154,
    commentCount: 11,
    engagementScore: 165,
    topic: "Cơ sở vật chất",
    sentimentScore: 0.95,
    aiSummary: "Ấn tượng với thiết kế mới của không gian tự học.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-18T14:00:00Z"),
  },
  {
    postId: "p25",
    author: "Đỗ Minh Quang",
    content:
      "Các chú bảo vệ KTX dạo này rất thân thiện, hay nhắc nhở sinh viên khóa xe cẩn thận. Cảm thấy rất an tâm.",
    postLink: "https://facebook.com/groups/ute/posts/125",
    postedAt: new Date("2026-04-25T22:30:00Z"),
    reactionCount: 132,
    commentCount: 5,
    engagementScore: 137,
    topic: "Ký túc xá",
    sentimentScore: 0.85,
    aiSummary:
      "Ghi nhận sự thay đổi tích cực trong thái độ của nhân viên an ninh KTX.",
    sentimentLabel: "Tích cực",
    analyzedAt: new Date("2026-04-26T08:00:00Z"),
  },

  // --- TRUNG LẬP (5 items - 17%) ---
  {
    postId: "p26",
    author: "Bùi Văn Nam",
    content:
      "Mọi người cho mình hỏi lịch nghỉ lễ 30/4 năm nay của trường mình có thông báo chính thức chưa nhỉ?",
    postLink: "https://facebook.com/groups/ute/posts/126",
    postedAt: new Date("2026-04-20T10:00:00Z"),
    reactionCount: 15,
    commentCount: 32,
    engagementScore: 47,
    topic: "Học vụ",
    sentimentScore: 0.5,
    aiSummary: "Câu hỏi về lịch nghỉ lễ chính thức.",
    sentimentLabel: "Trung lập",
    analyzedAt: new Date("2026-04-20T11:00:00Z"),
  },
  {
    postId: "p27",
    author: "Vũ Thị Lan",
    content:
      "Dịch vụ giặt sấy ở KTX giá 15k/lần, cũng tạm ổn nhưng mong có thêm máy để không phải đợi lâu.",
    postLink: "https://facebook.com/groups/ute/posts/127",
    postedAt: new Date("2026-04-14T16:00:00Z"),
    reactionCount: 24,
    commentCount: 8,
    engagementScore: 32,
    topic: "Ký túc xá",
    sentimentScore: 0.45,
    aiSummary: "Góp ý về việc tăng số lượng máy giặt tại KTX.",
    sentimentLabel: "Trung lập",
    analyzedAt: new Date("2026-04-14T18:00:00Z"),
  },
  {
    postId: "p28",
    author: "Trần Minh Hoàng",
    content:
      "Trường mình có câu lạc bộ nào về nhiếp ảnh không mọi người? Muốn tìm hội anh em cùng đam mê.",
    postLink: "https://facebook.com/groups/ute/posts/128",
    postedAt: new Date("2026-04-11T20:30:00Z"),
    reactionCount: 12,
    commentCount: 19,
    engagementScore: 31,
    topic: "Dịch vụ",
    sentimentScore: 0.55,
    aiSummary: "Tìm kiếm thông tin về các câu lạc bộ sở thích.",
    sentimentLabel: "Trung lập",
    analyzedAt: new Date("2026-04-12T08:00:00Z"),
  },
  {
    postId: "p29",
    author: "Phạm Hữu Nghĩa",
    content:
      "Nhà xe khu E dạo này thấy có dọn dẹp lại, nhìn cũng thoáng hơn chút nhưng vẫn cần mái che.",
    postLink: "https://facebook.com/groups/ute/posts/129",
    postedAt: new Date("2026-04-22T08:15:00Z"),
    reactionCount: 35,
    commentCount: 6,
    engagementScore: 41,
    topic: "Dịch vụ",
    sentimentScore: 0.5,
    aiSummary:
      "Ghi nhận sự cải thiện nhẹ tại bãi xe nhưng vẫn nhấn mạnh nhu cầu mái che.",
    sentimentLabel: "Trung lập",
    analyzedAt: new Date("2026-04-22T10:00:00Z"),
  },
  {
    postId: "p30",
    author: "Lê Thị Thắm",
    content:
      "Phòng đào tạo vừa có thông báo mới về chuẩn đầu ra tiếng Anh, các bạn K22 lưu ý nhé.",
    postLink: "https://facebook.com/groups/ute/posts/130",
    postedAt: new Date("2026-04-25T14:00:00Z"),
    reactionCount: 68,
    commentCount: 25,
    engagementScore: 93,
    topic: "Học vụ",
    sentimentScore: 0.5,
    aiSummary: "Chia sẻ thông tin về quy định chuẩn đầu ra ngoại ngữ.",
    sentimentLabel: "Trung lập",
    analyzedAt: new Date("2026-04-25T16:00:00Z"),
  },
];
